# Generated by Django 3.2.12 on 2023-02-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department_name',
            field=models.CharField(default=256, max_length=100),
        ),
    ]
